# Generated by Django 5.2.8 on 2026-01-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['due_date'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bill',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='recurrence_frequency',
            field=models.CharField(choices=[('none', 'One-time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(blank=True, choices=[('utilities', 'Utilities'), ('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('subscription', 'Subscription'), ('phone', 'Phone'), ('transportation', 'Transportation'), ('food', 'Food & Grocery'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('overdue', 'Overdue Bill'), ('due_soon', 'Bill Due Soon'), ('payment', 'Payment Confirmation'), ('reminder', 'Email Reminder Sent'), ('budget', 'Budget Alert'), ('info', 'Information')], default='info', max_length=20),
        ),
        migrations.CreateModel(
            name='BillAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bill_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bills.bill')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('account_details', models.CharField(blank=True, help_text='Account number or details', max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.paymentmethod'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reminders_enabled', models.BooleanField(default=True)),
                ('remind_days_before', models.IntegerField(default=3, help_text='Days before due date to send reminder')),
                ('daily_digest_enabled', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('subscription', 'Subscription'), ('phone', 'Phone'), ('transportation', 'Transportation'), ('food', 'Food & Grocery'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
