# Generated by Django 5.2.8 on 2026-01-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bill_options_bill_last_reminder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='recurrence_frequency',
            field=models.CharField(choices=[('none', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20),
        ),
    ]
